version: "3.7"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: izoldMyLove
      POSTGRES_USER: gonnagetbetter
      POSTGRES_DB: HCIS
    ports:
      - "5432:5432"

